data_path: data/Telco_customer_churn.xlsx
cols_to_drop:
  - 'CustomerID'
  - 'Country'
  - 'State'
  - 'City'
  - 'Zip Code'
  - 'Lat Long'
  - 'Latitude'
  - 'Longitude'
  - 'Churn Reason'
  - 'Count'
  - 'Churn Score'
  - 'Churn Label'

cols_to_select:
  - 'Gender'
  - 'Senior Citizen'
  - 'Partner'
  - 'Tenure Months'
  - 'Phone Service'
  - 'Internet Service'
  - 'Online Security'
  - 'Online Backup'
  - 'Device Protection'
  - 'Tech Support'
  - 'Streaming TV'
  - 'Streaming Movies'
  - 'Contract'
  - 'Paperless Billing'
  - 'Payment Method'
  - 'Monthly Charges'
  - 'Total Charges'
  - 'CLTV'